CREATE TABLE IF NOT EXISTS "wallet_transactions" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "userId" uuid NOT NULL, "amount" double precision NOT NULL, "type" character varying NOT NULL, "description" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_wallet_tx" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "print_jobs" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "userId" uuid NOT NULL, "centerId" uuid, "fileUrl" character varying NOT NULL, "fileName" character varying NOT NULL, "pages" integer NOT NULL, "copies" integer NOT NULL DEFAULT '1', "color" boolean NOT NULL DEFAULT false, "paperSize" character varying NOT NULL DEFAULT 'A4', "sides" character varying NOT NULL DEFAULT 'single', "cost" double precision NOT NULL DEFAULT '0', "status" character varying NOT NULL DEFAULT 'PENDING', "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_print_jobs" PRIMARY KEY ("id"));

DO $$ BEGIN CREATE TYPE "offers_type_enum" AS ENUM('PERCENTAGE', 'FIXED', 'TOKENS'); EXCEPTION WHEN duplicate_object THEN null; END $$;
CREATE TABLE IF NOT EXISTS "offers" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "code" character varying(50) NOT NULL, "title" character varying NOT NULL, "description" text, "type" "offers_type_enum" NOT NULL DEFAULT 'PERCENTAGE', "value" double precision NOT NULL, "minOrderAmount" double precision, "maxDiscount" double precision, "validFrom" TIMESTAMP NOT NULL, "validUntil" TIMESTAMP NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "usageCount" integer NOT NULL DEFAULT '0', "usageLimit" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_offers_code" UNIQUE ("code"), CONSTRAINT "PK_offers" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "offer_redemptions" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "offerId" uuid NOT NULL, "userId" uuid NOT NULL, "bookingId" uuid, "discountAmount" double precision, "redeemedAt" TIMESTAMP NOT NULL, CONSTRAINT "PK_offer_redemptions" PRIMARY KEY ("id"));

DO $$ BEGIN CREATE TYPE "support_tickets_category_enum" AS ENUM('BOOKING', 'PAYMENT', 'PRINT', 'OTHER'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE "support_tickets_priority_enum" AS ENUM('LOW', 'MEDIUM', 'HIGH'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE "support_tickets_status_enum" AS ENUM('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED'); EXCEPTION WHEN duplicate_object THEN null; END $$;

CREATE TABLE IF NOT EXISTS "support_tickets" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "userId" uuid NOT NULL, "centerId" uuid, "subject" character varying NOT NULL, "description" text NOT NULL, "category" "support_tickets_category_enum" NOT NULL DEFAULT 'OTHER', "priority" "support_tickets_priority_enum" NOT NULL DEFAULT 'MEDIUM', "status" "support_tickets_status_enum" NOT NULL DEFAULT 'OPEN', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_support_tickets" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "support_messages" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "ticketId" uuid NOT NULL, "userId" uuid, "isAdmin" boolean NOT NULL DEFAULT false, "message" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_support_msgs" PRIMARY KEY ("id"));

DO $$ BEGIN CREATE TYPE "referrals_status_enum" AS ENUM('PENDING', 'SUCCESSFUL', 'REWARDED'); EXCEPTION WHEN duplicate_object THEN null; END $$;
CREATE TABLE IF NOT EXISTS "referrals" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "referrerId" uuid NOT NULL, "referredEmail" character varying NOT NULL, "referredUserId" uuid, "code" character varying(50) NOT NULL, "status" "referrals_status_enum" NOT NULL DEFAULT 'PENDING', "rewardAmount" double precision NOT NULL DEFAULT '100', "rewardedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_referrals" PRIMARY KEY ("id"));

CREATE TABLE IF NOT EXISTS "notification_preferences" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "userId" uuid NOT NULL, "meetingReminders" boolean NOT NULL DEFAULT true, "billingAlerts" boolean NOT NULL DEFAULT true, "specialOffers" boolean NOT NULL DEFAULT true, "eventUpdates" boolean NOT NULL DEFAULT true, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_notif_pref_user" UNIQUE ("userId"), CONSTRAINT "PK_notif_prefs" PRIMARY KEY ("id"));

ALTER TABLE "customers" ADD COLUMN IF NOT EXISTS "userId" uuid;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "tokenBalance" integer NOT NULL DEFAULT '0';
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "deviceToken" character varying;
