packages:
  - 'apps/*'
  - 'libs/*'

allowBuilds:
  '@apollo/protobufjs': set this to true or false
  '@parcel/watcher': true
  '@swc/core': true
  bcrypt: set this to true or false
  better-sqlite3: set this to true or false
  detox: false
  dtrace-provider: false
  esbuild: set this to true or false
  less: true
  nx: true
  protobufjs: set this to true or false
  sharp: true
  sqlite3: true
  unrs-resolver: true
