packages:
  - 'apps/*'
  - 'libs/*'

allowBuilds:
  '@apollo/protobufjs': true
  '@parcel/watcher': true
  '@swc/core': true
  bcrypt: true
  better-sqlite3: true
  detox: false
  dtrace-provider: false
  esbuild: true
  less: true
  nx: true
  protobufjs: true
  sharp: true
  sqlite3: true
  unrs-resolver: true
