/**
 * File:        apps/web/src/lib/constants/operations.mock-data.ts
 * Module:      Web · Library · Constants
 * Purpose:     Mock data for operations routes — used as fallback when backend is unavailable
 *
 * Author:      AmanVatsSharma
 * Last-updated: 2026-07-02
 */

import type { MeetingRoom, Event, Request, EventStatus, EventType, RequestStatus, RequestType } from '../../types/operations';

// ─── Meeting Rooms ───────────────────────────────────────────────────

export const MOCK_MEETING_ROOMS: MeetingRoom[] = [
  {
    id: 'mr-1',
    name: 'Skyline Board Room',
    type: 'Conference Room',
    capacity: 20,
    status: 'AVAILABLE',
    locationName: 'Floor 3 — Main Wing',
    floorId: 'f3',
    centerId: 'c1',
    minBookingDuration: 30,
    maxBookingDuration: 480,
    amenities: ['Video Conferencing', 'Whiteboard', 'Projector', 'Coffee Machine', 'Phone Booth'],
    hourlyRate: 25,
    active: true,
    createdAt: '2025-01-15T08:00:00.000Z',
    updatedAt: '2025-06-20T14:30:00.000Z',
  },
  {
    id: 'mr-2',
    name: 'Innovation Hub',
    type: 'Collaborative Space',
    capacity: 12,
    status: 'BOOKED',
    locationName: 'Floor 2 — East Wing',
    floorId: 'f2',
    centerId: 'c1',
    minBookingDuration: 30,
    maxBookingDuration: 240,
    amenities: ['Smart Board', 'Video Conferencing', 'Flexible Seating', 'TV Display'],
    hourlyRate: 18,
    active: true,
    createdAt: '2025-01-15T08:00:00.000Z',
    updatedAt: '2025-06-20T14:30:00.000Z',
  },
  {
    id: 'mr-3',
    name: 'Focus Pod',
    type: 'Private Booth',
    capacity: 2,
    status: 'OCCUPIED',
    locationName: 'Floor 1 — Quiet Zone',
    floorId: 'f1',
    centerId: 'c1',
    minBookingDuration: 15,
    maxBookingDuration: 120,
    amenities: ['Monitor', 'Ergonomic Chair', 'Noise Cancelling'],
    hourlyRate: 8,
    active: true,
    createdAt: '2025-01-15T08:00:00.000Z',
    updatedAt: '2025-06-20T14:30:00.000Z',
  },
  {
    id: 'mr-4',
    name: 'Creativity Lab',
    type: 'Workshop Room',
    capacity: 30,
    status: 'AVAILABLE',
    locationName: 'Floor 3 — West Wing',
    floorId: 'f3',
    centerId: 'c1',
    minBookingDuration: 60,
    maxBookingDuration: 480,
    amenities: ['Whiteboard Walls', 'Projector', 'Video Conferencing', 'Breakout Areas', 'TV Display'],
    hourlyRate: 30,
    active: true,
    createdAt: '2025-01-15T08:00:00.000Z',
    updatedAt: '2025-06-20T14:30:00.000Z',
  },
  {
    id: 'mr-5',
    name: 'Executive Suite',
    type: 'Private Office',
    capacity: 6,
    status: 'MAINTENANCE',
    locationName: 'Floor 4 — Premium Wing',
    floorId: 'f4',
    centerId: 'c1',
    minBookingDuration: 30,
    maxBookingDuration: 240,
    amenities: ['Video Conferencing', 'Coffee Machine', 'Private Bath', 'Natural Light'],
    hourlyRate: 40,
    active: true,
    createdAt: '2025-01-15T08:00:00.000Z',
    updatedAt: '2025-06-20T14:30:00.000Z',
  },
  {
    id: 'mr-6',
    name: 'Huddle Room A',
    type: 'Meeting Room',
    capacity: 6,
    status: 'AVAILABLE',
    locationName: 'Floor 2 — Central Corridor',
    floorId: 'f2',
    centerId: 'c1',
    minBookingDuration: 15,
    maxBookingDuration: 120,
    amenities: ['TV Display', 'Video Conferencing'],
    hourlyRate: 12,
    active: true,
    createdAt: '2025-01-15T08:00:00.000Z',
    updatedAt: '2025-06-20T14:30:00.000Z',
  },
  {
    id: 'mr-7',
    name: 'Seminar Hall',
    type: 'Conference Room',
    capacity: 50,
    status: 'AVAILABLE',
    locationName: 'Floor 1 — Events Area',
    floorId: 'f1',
    centerId: 'c1',
    minBookingDuration: 60,
    maxBookingDuration: 480,
    amenities: ['Stage', 'Projector', 'PA System', 'Video Conferencing', 'Recording Setup'],
    hourlyRate: 50,
    active: true,
    createdAt: '2025-01-15T08:00:00.000Z',
    updatedAt: '2025-06-20T14:30:00.000Z',
  },
  {
    id: 'mr-8',
    name: 'Zen Room',
    type: 'Wellness Room',
    capacity: 4,
    status: 'AVAILABLE',
    locationName: 'Floor 3 — Wellness Zone',
    floorId: 'f3',
    centerId: 'c1',
    minBookingDuration: 15,
    maxBookingDuration: 60,
    amenities: ['Meditation Cushions', 'Aromatherapy', 'Ambient Sound'],
    hourlyRate: 6,
    active: true,
    createdAt: '2025-01-15T08:00:00.000Z',
    updatedAt: '2025-06-20T14:30:00.000Z',
  },
];

// ─── Events ─────────────────────────────────────────────────────────

export const MOCK_EVENTS: Event[] = [
  {
    id: 'evt-1',
    centerId: 'c1',
    meetingRoomId: 'mr-1',
    requestedById: 'u-1',
    title: 'Q2 All-Hands Review',
    description: 'Quarterly all-hands review with leadership updates.',
    company: 'SpaceJam HQ',
    eventDate: new Date(new Date().setDate(new Date().getDate() + 2)).toISOString().split('T')[0],
    startTime: '10:00',
    endTime: '12:00',
    durationMinutes: 120,
    attendeesCount: 25,
    type: 'MEETING_ROOM',
    status: 'CONFIRMED',
    specialRequests: 'Video conference setup and lunch catering',
    addons: ['Catering', 'AV Support'],
    cost: 600,
    notes: 'CEO presenting Q2 results',
    createdAt: '2025-06-01T09:00:00.000Z',
    updatedAt: '2025-06-25T11:00:00.000Z',
  },
  {
    id: 'evt-2',
    centerId: 'c1',
    meetingRoomId: 'mr-4',
    requestedById: 'u-2',
    title: 'Design Thinking Workshop',
    description: 'Full-day interactive workshop for the product team.',
    company: 'TechCorp',
    eventDate: new Date(new Date().setDate(new Date().getDate() + 5)).toISOString().split('T')[0],
    startTime: '09:00',
    endTime: '17:00',
    durationMinutes: 480,
    attendeesCount: 28,
    type: 'WORKSHOP',
    status: 'PENDING',
    specialRequests: 'Post-it notes and markers for breakout sessions',
    addons: ['Catering', 'Materials'],
    cost: 1440,
    notes: 'External facilitator confirmed',
    createdAt: '2025-06-15T14:00:00.000Z',
    updatedAt: '2025-06-20T10:30:00.000Z',
  },
  {
    id: 'evt-3',
    centerId: 'c1',
    meetingRoomId: 'mr-7',
    requestedById: 'u-3',
    title: 'Annual Tech Meetup',
    description: 'Industry networking and tech showcase event.',
    company: 'DevCommunity',
    eventDate: new Date(new Date().setDate(new Date().getDate() + 10)).toISOString().split('T')[0],
    startTime: '13:00',
    endTime: '20:00',
    durationMinutes: 420,
    attendeesCount: 120,
    type: 'CONFERENCE',
    status: 'CONFIRMED',
    specialRequests: 'PA system, recording setup, and stage layout',
    addons: ['Catering', 'AV Support', 'Recording', 'Stage Setup'],
    cost: 6000,
    notes: 'Sponsor logos TBD',
    createdAt: '2025-05-20T08:00:00.000Z',
    updatedAt: '2025-06-18T16:00:00.000Z',
  },
  {
    id: 'evt-4',
    centerId: 'c1',
    meetingRoomId: 'mr-2',
    requestedById: 'u-4',
    title: 'Investor Pitch Session',
    description: 'Monthly investor pitch — three startups presenting.',
    company: 'VentureFund',
    eventDate: new Date(new Date().setDate(new Date().getDate() + 1)).toISOString().split('T')[0],
    startTime: '14:00',
    endTime: '17:00',
    durationMinutes: 180,
    attendeesCount: 18,
    type: 'PRIVATE_EVENT',
    status: 'PENDING',
    specialRequests: 'Confidential NDA required',
    addons: ['Catering', 'NDA Packets'],
    cost: 900,
    notes: 'NDA packets must be printed before event',
    createdAt: '2025-06-26T10:00:00.000Z',
    updatedAt: '2025-06-26T10:00:00.000Z',
  },
  {
    id: 'evt-5',
    centerId: 'c1',
    meetingRoomId: 'mr-6',
    requestedById: 'u-5',
    title: 'Sprint Retrospective',
    description: 'Bi-weekly team retrospective for Engineering pod.',
    company: 'SpaceJam HQ',
    eventDate: new Date().toISOString().split('T')[0],
    startTime: '16:00',
    endTime: '17:30',
    durationMinutes: 90,
    attendeesCount: 8,
    type: 'MEETING_ROOM',
    status: 'CONFIRMED',
    specialRequests: undefined,
    addons: undefined,
    cost: 90,
    notes: 'Use sticky notes for retro board',
    createdAt: '2025-06-20T09:00:00.000Z',
    updatedAt: '2025-06-28T15:00:00.000Z',
  },
  {
    id: 'evt-6',
    centerId: 'c1',
    meetingRoomId: 'mr-3',
    requestedById: 'u-6',
    title: 'Client Onboarding',
    description: '1-on-1 onboarding session with new enterprise client.',
    company: 'Enterprise Solutions Ltd',
    eventDate: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString().split('T')[0],
    startTime: '11:00',
    endTime: '12:30',
    durationMinutes: 90,
    attendeesCount: 2,
    type: 'MEETING_ROOM',
    status: 'COMPLETED',
    specialRequests: 'NDA required, laptop setup',
    addons: ['NDA Packet'],
    cost: 60,
    notes: 'Client is very happy — upsell opportunity',
    createdAt: '2025-06-15T08:00:00.000Z',
    updatedAt: '2025-06-28T14:00:00.000Z',
  },
  {
    id: 'evt-7',
    centerId: 'c1',
    meetingRoomId: 'mr-1',
    requestedById: 'u-7',
    title: 'Product Roadmap Review',
    description: 'Half-day strategic roadmap planning with stakeholders.',
    company: 'SpaceJam HQ',
    eventDate: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString().split('T')[0],
    startTime: '09:00',
    endTime: '13:00',
    durationMinutes: 240,
    attendeesCount: 15,
    type: 'CONFERENCE',
    status: 'CANCELLED',
    specialRequests: undefined,
    addons: undefined,
    cost: 0,
    notes: 'Rescheduled due to CEO illness',
    createdAt: '2025-06-10T11:00:00.000Z',
    updatedAt: '2025-06-22T09:00:00.000Z',
  },
];

// ─── Requests ────────────────────────────────────────────────────────

export const MOCK_REQUESTS: Request[] = [
  {
    id: 'req-1',
    centerId: 'c1',
    assignedToId: 'u-10',
    type: 'MAINTENANCE',
    title: 'AC Repair in Conference Room A',
    description: 'Air conditioner not cooling in the conference room. Temperature around 28°C.',
    urgency: 'HIGH',
    status: 'PENDING',
    dueDate: new Date().toISOString().split('T')[0],
    completedDate: null,
    resolution: null,
    cost: 0,
    attachedFile: null,
    metadata: null,
    createdAt: '2025-06-29T08:00:00.000Z',
    updatedAt: '2025-06-29T08:00:00.000Z',
  },
  {
    id: 'req-2',
    centerId: 'c1',
    requestedById: 'u-9',
    assignedToId: 'u-11',
    type: 'INTERNET_SUPPORT',
    title: 'WiFi Outage in Floor 2',
    description: 'All WiFi access points on Floor 2 appear offline since 9 AM. Multiple members affected.',
    urgency: 'HIGH',
    status: 'IN_PROGRESS',
    dueDate: new Date().toISOString().split('T')[0],
    completedDate: null,
    resolution: 'ISP outage — currently escalating',
    cost: 0,
    attachedFile: null,
    metadata: null,
    createdAt: '2025-06-30T09:15:00.000Z',
    updatedAt: '2025-06-30T10:30:00.000Z',
  },
  {
    id: 'req-3',
    centerId: 'c1',
    requestedById: 'u-12',
    assignedToId: undefined,
    type: 'PRINTER_ACCESS',
    title: 'New Printer Installation',
    description: 'Need a new high-speed printer installed in the quiet zone on Floor 3.',
    urgency: 'MEDIUM',
    status: 'PENDING',
    dueDate: new Date(new Date().setDate(new Date().getDate() + 7)).toISOString().split('T')[0],
    completedDate: null,
    resolution: null,
    cost: 500,
    attachedFile: null,
    metadata: null,
    createdAt: '2025-06-25T13:00:00.000Z',
    updatedAt: '2025-06-25T13:00:00.000Z',
  },
  {
    id: 'req-4',
    centerId: 'c1',
    requestedById: 'u-13',
    assignedToId: 'u-10',
    type: 'CLEANING',
    title: 'Deep Clean — Floor 4',
    description: 'Scheduled quarterly deep clean for the premium wing.',
    urgency: 'LOW',
    status: 'IN_PROGRESS',
    dueDate: new Date(new Date().setDate(new Date().getDate() + 3)).toISOString().split('T')[0],
    completedDate: null,
    resolution: null,
    cost: 1200,
    attachedFile: null,
    metadata: null,
    createdAt: '2025-06-20T10:00:00.000Z',
    updatedAt: '2025-06-28T08:00:00.000Z',
  },
  {
    id: 'req-5',
    centerId: 'c1',
    requestedById: 'u-14',
    assignedToId: 'u-11',
    type: 'SUPPLIES',
    title: 'Whiteboard Marker Restock',
    description: 'All markers across meeting rooms are dried up. Need restock of 50 units.',
    urgency: 'LOW',
    status: 'COMPLETED',
    dueDate: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString().split('T')[0],
    completedDate: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString().split('T')[0],
    resolution: 'Restocked all 12 meeting rooms with black, red, and blue markers.',
    cost: 75,
    attachedFile: null,
    metadata: null,
    createdAt: '2025-06-20T11:00:00.000Z',
    updatedAt: '2025-06-28T09:00:00.000Z',
  },
  {
    id: 'req-6',
    centerId: 'c1',
    requestedById: 'u-15',
    assignedToId: undefined,
    type: 'SECURITY',
    title: 'CCTV Camera Replacement',
    description: 'CCTV camera in the main entrance is flickering and goes offline frequently.',
    urgency: 'HIGH',
    status: 'PENDING',
    dueDate: new Date().toISOString().split('T')[0],
    completedDate: null,
    resolution: null,
    cost: 300,
    attachedFile: null,
    metadata: null,
    createdAt: '2025-06-30T16:00:00.000Z',
    updatedAt: '2025-06-30T16:00:00.000Z',
  },
  {
    id: 'req-7',
    centerId: 'c1',
    requestedById: 'u-16',
    assignedToId: 'u-10',
    type: 'FURNITURE_UPGRADE',
    title: 'Ergonomic Chair Replacement',
    description: '5 chairs in Floor 2 collaborative area need replacement. Armrests are broken.',
    urgency: 'MEDIUM',
    status: 'COMPLETED',
    dueDate: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString().split('T')[0],
    completedDate: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString().split('T')[0],
    resolution: 'Replaced all 5 chairs with new ergonomic models.',
    cost: 1500,
    attachedFile: null,
    metadata: null,
    createdAt: '2025-06-15T09:00:00.000Z',
    updatedAt: '2025-06-27T15:00:00.000Z',
  },
  {
    id: 'req-8',
    centerId: 'c1',
    requestedById: 'u-17',
    assignedToId: undefined,
    type: 'EVENT_BOOKING',
    title: 'Community Yoga Session',
    description: 'Weekly community yoga session for members — needs floor mats and speaker setup.',
    urgency: 'LOW',
    status: 'REJECTED',
    dueDate: '',
    completedDate: '',
    resolution: 'Rejected — wellness room already fully booked during preferred slot.',
    cost: 0,
    attachedFile: null,
    metadata: null,
    createdAt: '2025-06-22T12:00:00.000Z',
    updatedAt: '2025-06-27T09:00:00.000Z',
  },
  {
    id: 'req-9',
    centerId: 'c1',
    requestedById: 'u-18',
    assignedToId: 'u-11',
    type: 'MAINTENANCE',
    title: 'Elevator Inspection',
    description: 'Scheduled quarterly elevator maintenance and safety inspection.',
    urgency: 'MEDIUM',
    status: 'COMPLETED',
    dueDate: new Date(new Date().setDate(new Date().getDate() - 10)).toISOString().split('T')[0],
    completedDate: new Date(new Date().setDate(new Date().getDate() - 10)).toISOString().split('T')[0],
    resolution: 'Inspection passed. Minor lubrication applied to door mechanisms.',
    cost: 450,
    attachedFile: null,
    metadata: null,
    createdAt: '2025-06-10T08:00:00.000Z',
    updatedAt: '2025-06-20T11:00:00.000Z',
  },
  {
    id: 'req-10',
    centerId: 'c1',
    requestedById: 'u-19',
    assignedToId: undefined,
    type: 'OTHER',
    title: 'Visitor Badge Printer',
    description: 'Visitor badge printer on the reception desk is jamming frequently. Needs repair or replacement.',
    urgency: 'MEDIUM',
    status: 'CANCELLED',
    dueDate: '',
    completedDate: '',
    resolution: 'Cancelled — issue resolved by IT department themselves.',
    cost: 0,
    attachedFile: null,
    metadata: null,
    createdAt: '2025-06-18T10:00:00.000Z',
    updatedAt: '2025-06-26T14:00:00.000Z',
  },
];

// ─── Event Statistics ────────────────────────────────────────────────

export const MOCK_EVENT_STATS = {
  totalEvents: 7,
  pendingEvents: 2,
  confirmedEvents: 3,
  completedEvents: 1,
  cancelledEvents: 1,
};

// ─── Request Statistics ─────────────────────────────────────────────

export const MOCK_REQUEST_STATS = {
  totalRequests: 10,
  pendingRequests: 5,
  inProgressRequests: 2,
  completedRequests: 3,
  cancelledRequests: 2,
  highUrgencyRequests: 4,
};
